# Controlabilidad de sistemas dinámicos

---

<ul>
    <li><strong>Autor:</strong> Jesús Emmanuel Solís Pérez </li>
    <li><strong>Contacto:</strong> <a href="mailto:jsolisp@unam.mx">jsolisp@unam.mx</a>
</ul>

---

## Concepto de controlabilidad

Considere un sistema $n$-dimensional en representación de espacio-estado

\begin{equation}
 \label{eqn:ree}
 \begin{aligned}
  \dot{x} &= Ax + Bu, \\
  y &= Cx + Du,
 \end{aligned}
\end{equation}

donde $A$, $B$, $C$ son matrices de dimensión $n\times n$, $n\times 1$, y $1\times n$, respectivamente. Además, $D$ es escalar.

**Definición 1.** *El sistema \eqref{eqn:ree} es **controlable** si cualquier estado se puede transferir a cualquier otro estado en un tiempo finito aplicando una entrada.*

**Teorema 1.** *Para cada $y$, existe una solución $x$ en $Ax=y$ si y sólo si $A$ es de rango completo.*

Recordemos que la solución al sistema \eqref{eqn:ree} dado una entrada $u(t)$ y una c.i. $x(0)$ está dado como sigue

\begin{equation}
 \label{eqn:solution}
 x(t) = \underbrace{e^{At}x(0)}_{\text{Zero-Input Response}} + \underbrace{e^{At}\int_{0}^{t} e^{-A\tau}Bu(\tau)\mathrm{d}\tau}_{\text{Zero-State Response}},
\end{equation}

y

\begin{equation}
 y(t) = ce^{At}x(0) + ce^{At}\int_{0}^{t}e^{-A\tau}Bu(\tau)\mathrm{d}\tau + Du(t).
\end{equation}

Reescribiendo \eqref{eqn:solution}, tenemos

\begin{equation}
 \begin{aligned}
  x(t) - e^{At}x(0) &= \int_{0}^{t} \left[ I + A(t-\tau) + A^{2}\frac{(t-\tau)^{2}}{2} + \cdots \right] Bu(\tau)\mathrm{d}\tau, \\
  &= B \int_{0}^{t}u(\tau)\mathrm{d}\tau + AB \int_{0}^{t}(t - \tau)u(\tau)\mathrm{d}\tau \\
  &+ A^{2}B \int_{0}^{t} \frac{1}{2}(t-\tau)^{2}u(\tau)\mathrm{d}\tau + \cdots, \\
  &= \begin{bmatrix} B & AB & A^{2}B \cdots \end{bmatrix}
  \begin{bmatrix}
   \int_{0}^{t}u(\tau)\mathrm{d}\tau \\
   \int_{0}^{t}(t-\tau)u(\tau)\mathrm{d}\tau \\
   \int_{0}^{t}\frac{1}{2}(t-\tau)^{2}u(\tau)\mathrm{d}\tau \\
   \vdots
  \end{bmatrix}
 \end{aligned}
\end{equation}

Utilizando el **Teorema 1**, tenemos que para cualquier $x(0)$ y $x(t)$, una solución $u(t)$ existe si y sólo si la matriz

\begin{equation}
 \label{eqn:nocontrollability}
 \begin{bmatrix}
  B & AB & A^{2}B & \cdots & A^{n-1}B & \cdots
 \end{bmatrix}
\end{equation}

tiene rango $n$.

Utilizando el teorema de Cayley-Hamilton, la matriz \eqref{eqn:nocontrollability} tiene rango $n$ si y sólo si la matriz $n\times n$

\begin{equation}
 \label{eqn:controllability}
 U = \begin{bmatrix}
  B & AB & A^{2}B & \cdots & A^{n-1}B
 \end{bmatrix}
\end{equation}

tiene rango $n$.

En resumen, el sistema \eqref{eqn:ree} es controlable si la matriz \eqref{eqn:controllability} tiene rango $n$, o bien, $\text{det}\{U\} \neq 0$.

**Observación.** La matriz \eqref{eqn:controllability} es llamada **matriz de controlabilidad**.

### Ejemplo 1

Considere la siguiente función de transferencia

\begin{equation}
 G(s) = \frac{N(s)}{D(s)} = \frac{2s-1}{s^{2}-1.5s-1} = \frac{2s-1}{(s-2)\left(s+\frac{1}{2}\right)}
\end{equation}

### Ejemplo 2

Considere la siguiente función de transferencia

\begin{equation}
 G(s) = \frac{N(s)}{D(s)} = \frac{2s+1}{s^{2}-1.5s-1} = \frac{2s+1}{(s-2)\left(s+\frac{1}{2}\right)}
\end{equation}

### Ejemplo 3

Considere el sistema de equilibrio que se muestra en la siguiente Figura.

![Sistema de equilibrio](../figures/Cart_pendulum.png "Sistema de equilibrio")

En este ejemplo, el centro de masa se equilibra por encima de un punto de pivote. Un ejemplo de ello se puede ver en la película "Guardia de supermercado".

![Paul Blart](../figures/guardia_supermercado.jpg)

El modelo no lineal para el sistema de equilibrio se muestra a continuación

\begin{equation}
 \begin{aligned}
  (M + m)\ddot{p} - ml \cos(\theta)\ddot{\theta} &= -c\dot{p} - ml \sin(\theta)\dot{\theta}^{2} + F, \\
  (J + ml^{2})\ddot{\theta} - ml\cos(\theta)\ddot{p} &= -\gamma \dot{\theta} + mgl\sin(\theta),
 \end{aligned}
\end{equation}

donde $M$ es la masa de la base, $m$ y $J$ la masa y el momento de inercia del sistema a ser balanceado. Además, $l$ denota la distancia de la base al centro de masa del cuerpo balanceado, $c$ y $\gamma$ son los coeficientes de fricción viscosa así como $g$ representa la aceleración debido a la gravedad.

La dinámica del sistema en espacio de estado se puede obtener considerando como variables de estado$x = (p,\theta,\dot{p},\dot{\theta})$, la entrada como $u=F$ y salida como $y=(p,\theta)$.

Si definimos la masa total y la inercia total como sigue, tenemos

\begin{equation}
 M_{t} = M + m, \quad J_{t} = J + ml^{2}.
\end{equation}

Por consiguiente, podemos representar las ecuaciones de movimiento como sigue

\begin{equation}
 \begin{bmatrix}
  \dot{p} \\
  \dot{\theta} \\
  \ddot{p} \\
  \ddot{\theta}
 \end{bmatrix} = 
 \begin{bmatrix}
  \dot{p} \\
  \dot{\theta} \\
  \frac{-mls_{\theta}\dot{\theta}^{2} + mg(ml^{2}/J_{t})s_{\theta}c_{\theta} - c\dot{p} - \gamma l m c_{\theta}\dot{\theta} + u}{M_{t} - m(ml^{2}/J_{t})c_{\theta}^{2}}\\
  \frac{-ml^{2}s_{\theta}c_{\theta}\dot{\theta}^{2} + M_{t}gls_{\theta} - cl c_{\theta} \dot{p} - \gamma(M_{t}/m)\dot{\theta} + lc_{\theta}u}{J_{t}(M_{t}/m) - m(lc_{\theta})^{2}}
 \end{bmatrix},
\end{equation}

\begin{equation}
 y = \begin{bmatrix}
  p \\
  \theta
 \end{bmatrix},
\end{equation}

donde $c_{\theta} = \cos(\theta)$ y $s_{\theta} = \sin(\theta)$.

En ocaciones, el ángulo $\theta$ puede ser cercano a $0$. Por consiguiente, podemos hacer las siguientes suposiciones: $\sin(\theta) \approx \theta$ y $\cos(\theta) \approx 1$. Además, si $\dot{\theta}$ es pequeño, entonces se puede menospreciar los términos cuadráticos y superiores en $\dot{\theta}$.

Reescribiendo el sistema a partir de estas suposiciones, tenemos

\begin{equation}
 \begin{bmatrix}
  \dot{p} \\
  \dot{\theta} \\
  \ddot{p} \\
  \ddot{\theta}
 \end{bmatrix} = 
 \begin{bmatrix}
  0 & 0 & 1 & 0 \\
  0 & 0 & 0 & 1 \\
  0 & m^{2}l^{2}g/\mu & -cJ_{t}/\mu & -\gamma J_{t}lm/\mu \\ 
  0 & M_{t}mgl/\mu & -clm/\mu & -\gamma M_{t}/\mu
 \end{bmatrix}
 \begin{bmatrix}
  p \\
  \theta \\
  \dot{p} \\
  \dot{\theta}
 \end{bmatrix} +
 \begin{bmatrix}
  0 \\
  0 \\
  J_{t}/\mu \\
  lm/\mu
 \end{bmatrix}u,
\end{equation}

\begin{equation}
 y = 
 \begin{bmatrix}
  1 & 0 & 0 & 0 \\
  0 & 1 & 0 & 0
 \end{bmatrix}x,
\end{equation}

donde $\mu = M_{t}J_{t} - m^{2}l^{2}$.

Encuentre los puntos de equilibrio del sistema y linealice alrededor de uno de ellos. Además, considere $c = \gamma = 0$.

### Ejemplo 4

El péndulo invertido es una variación del sistema mostrado en el ejemplo anterior. La diferencia radica en que la base $p$ no necesita estar controlada y lo único que se desea es estabilizar la horientación vertical de la barra. Este sistema se puede apreciar en la siguiente Figura.

![Péndulo invertido](../figures/inverted_pendulum.png "Péndulo invertido")

El sistema de ecuaciones que describe la dinámica del péndulo simple está dado como sigue

\begin{equation}
 \begin{bmatrix}
  \dot{\theta} \\
  \ddot{\theta}
 \end{bmatrix} = 
 \begin{bmatrix}
  \dot{\theta} \\
  \frac{mgl}{J_{t}}\sin(\theta) - \frac{\gamma}{J_{t}}\dot{\theta} + \frac{l}{J_{t}}\cos(\theta)u
 \end{bmatrix}, \quad
 y = \theta,
\end{equation}

donde $\gamma$ es el coeficiente de fricción rotacional, $J_{t} = J + ml^{2}$ y $u$ es la fuerza aplicada a la base.

---

## Formas canónicas de controlabilidad

Considere el caso general representado en función de transferencia

\begin{equation}
 G(s) = \frac{N(s)}{D(s)} = \frac{b_{1}s^{3} + b_{2}s^{2} + b_{3}s + b_{4}}{s^{4} + a_{1}s^{3} + a_{2}s^{2} + a_{3}s + a_{4}}.
\end{equation}

La forma de realización controlable del sistema anterior es

\begin{equation}
 \begin{aligned}
  \dot{x} &= \begin{bmatrix}
   -a_{1} & -a_{2} & -a_{3} & -a_{4} \\
   1 & 0 & 0 & 0 \\
   0 & 1 & 0 & 0 \\
   0 & 0 & 1 & 0 \\
  \end{bmatrix} x + 
  \begin{bmatrix}
   1 \\
   0 \\
   0 \\
   0
  \end{bmatrix}u, \\
  y &= \begin{bmatrix} b_{1} & b_{2} & b_{3} & b_{4} \end{bmatrix}x,
 \end{aligned}
\end{equation}

donde la matriz de controlabilidad puede ser obtenida como sigue

\begin{equation}
 \label{eqn:U}
 U = \begin{bmatrix}
  1 & -a_{1} & e_{2} & e_{3} \\
  0 & 1 & -a_{1} & e_{2} \\
  0 & 0 & 1 & -a_{1} \\
  0 & 0 & 0 & 1
 \end{bmatrix},
\end{equation}

con $e_{2} := -a_{2} + a_{1}^{2}$ y $e_{3} := -a_{3} + 2a_{1}a_{2}-a_{1}^{3}$. 

**Observación.** La matriz \eqref{eqn:U} es una matriz triangular cuyo determinante siempre es 1. Por consiguiente, siempre es controlable y es la razón por la que se llama *forma controlable*.

---

## Estabilización por retroalimentación de estado

Supongamos que se desea controlar un sistema en representación de espacio de estados lineal. Por simplicidad consideramos que tiene una sola entrada y que la ley de control de retroalimentación parte de la idea de que el sistema en lazo cerrado tiene eigenvalores deseados.

Para ello, considere el siguiente sistema $n$-dimensional en representación de espacio-estado

\begin{equation}
 \label{eqn:ree_2}
 \begin{aligned}
  \dot{x} &= Ax + Bu, \\
  y &= Cx + Du,
 \end{aligned}
\end{equation}

con función de transferencia

\begin{equation}
 G(s) = C(sI - A)^{-1}B.
\end{equation}

El objetivo es llevar la salida $y$ al valor de referencia $r$ a partir de la medición de los estados $x$. Para ello, consideramos que la ley de control invariante en el tiempo definida como $u$ es una función del estado y la referencia como se muestra a continuación

\begin{equation}
 \label{eqn:u_ctrl}
 u = r - Kx,
\end{equation}
donde $K = \begin{bmatrix} k_{1} & k_{2} & \cdots & k_{n} \end{bmatrix}$ es un vector real de dimensión $1\times n$.

La ecuación \eqref{eqn:u_ctrl} es conocida como \myindex{retroalimentación de estado de ganancia constante} o simplemente \myindex{retroalimentación de estado} \citep{aastrom2021feedback}.

Sustituyendo \eqref{eqn:u_ctrl} en \eqref{eqn:ree_2}, tenemos

\begin{equation}
 \begin{aligned}
  \dot{x} &= Ax - BKx + Br, \\ &= (A-BK)x + Br, \\
  y &= Cx,
 \end{aligned}
\end{equation}
con función de transferencia

\begin{equation}
 G_{o}(s) = C(sI - A + Bk)^{-1}B,
\end{equation}
con polinomio caracteristico

\begin{equation}
 \label{eqn:pol_car_cl}
 p(s) = s^{n} + a_{1}s^{n-1}+\cdots+a_{n-1}s + a_{n}.
\end{equation}

El cálculo de la ganancia de retroalimentación $K$ para que el sistema de lazo cerrado con polinomio \eqref{eqn:pol_car_cl} se conoce como \myindex{asignación de eigenvalores} o \myindex{localización de polos}.

Por otro lado, si consideramos el esquema de control mostrado en la \cref{fig:state_feedback}, tenemos la siguiente ley de control

\begin{equation}
 u = -Kx + k_{r}r,
\end{equation}
donde el sistema en lazo cerrado se expresa como sigue

\begin{equation}
 \begin{aligned}
  \dot{x} &= (A-BK)x + Bk_{r}r, \\
  y &= Cx.
 \end{aligned}
\end{equation}

**Observación.** Si $(A,B)$ es controlable, entonces los eigenvalores de $(A-Bk)$ pueden ser asignados arbitrariamente escogiendo una ganancia de retroalimentación real $k$.

### Procedimiento para la asignación de eigenvalores

1. Calcule el polinomio característico de $A:\Delta (\lambda) = \text{det}(\lambda I-A)$.
2. Calcule el polinomio característico deseado 

\begin{equation}
  \begin{aligned}
   \bar{\Delta}(\lambda) &= (\lambda-\lambda_{1})(\lambda-\lambda_{2})(\lambda-\lambda_{3})\cdots (\lambda-\lambda_{n}), \\
   &= \lambda^{n} + \bar{a}_{1}\lambda^{n-1} + \bar{a}_{2}\lambda^{n-2} + \dots + \bar{a}_{n}.
  \end{aligned}
 \end{equation}

3. Calcule la ganancia de retroalimentación para la ecuación equivalente en la forma controlable

\begin{equation}
  \bar{k} = \begin{bmatrix} \bar{a}_{1}-a_{1} & \bar{a}_{2}-a_{2} & \cdots & \bar{a}_{n}-a_{n} \end{bmatrix}.
 \end{equation}

4. Calcule la transformación equivalente

\begin{equation}
  S:=P^{-1} = \begin{bmatrix} B & AB & A^{2}B & A^{3}B \end{bmatrix}
  \begin{bmatrix}
   1 & a_{1} & a_{2} & \dots & a_{n-1} \\
   0 & 1 & a_{1} & \dots & a_{n-2} \\
   0 & 0 & 1 & \dots & a_{n-3} \\
   \vdots & \vdots & \vdots & \dots & \vdots \\
   0 & 0 & 0 & \dots & 1
  \end{bmatrix}.
 \end{equation}
5. Calcule la ganancia de retroalimentación $k=\bar{k}P = \bar{k}S^{-1}$.

**Observación.** Existen otras formas para obtener la ganancia de retroalimentación $k$, una de ellas es la *fórmula de Ackerman* dada por la siguiente ecuación

\begin{equation}
 \begin{aligned}
  k &= \begin{bmatrix} 0 & 0 & 0 & \cdots & 1 \end{bmatrix} \begin{bmatrix} B & AB & A^{2}B & \cdots & A^{n}B \end{bmatrix}^{-1}\bar{\Delta}(A),
 \end{aligned}
\end{equation}

donde $\bar{\Delta}(s)$ es el polinomio característico de $(A-Bk))$, por lo tanto $\bar{\Delta}(A) \neq 0$.

#### Ejemplo 1

Considere el siguiente sistema en representación de espacio de estados

\begin{equation}
 \begin{aligned}
  \dot{x} &= \begin{bmatrix}
   \dot{x}_{1} \\
   \dot{x}_{2}
  \end{bmatrix} = 
  \begin{bmatrix}
   0 & 1 \\
   0 & -1
  \end{bmatrix}x + 
  \begin{bmatrix}
   0 \\
   10
  \end{bmatrix}u, \\
  y &= \begin{bmatrix} 1 & 0 \end{bmatrix}x
 \end{aligned}
\end{equation}

cuya función de transferencia es

\begin{equation}
 G(s) = \frac{10}{s^{2} + s}.
\end{equation}

Encuentre la ganancia de retroalimentación $k$ en $u=r-kx$ tal que la ecuación resultante tenga sus eigenvalores en $-2\pm j2$.

In [1]:
import numpy as np
import control as ctrl
import matplotlib.pyplot as plt

In [2]:
#System matrices
A = np.array([[0, 1], [0, -1]])
B = np.array([[0], [10]])
C = np.array([[1, 0]])

In [3]:
sys = ctrl.ss(A, B, C, 0)
sys

<LinearIOSystem:sys[2]:['u[0]']->['y[0]']>

In [4]:
# Controllabilty matrix step by step
U = np.hstack((B, A@B)) # np.concatenate((B, A@B), axis=1)
U

array([[  0,  10],
       [ 10, -10]])

In [5]:
# Controllabilty matrix
U = ctrl.ctrb(A, B)
U

array([[  0.,  10.],
       [ 10., -10.]])

In [6]:
n = np.linalg.matrix_rank(U)
n

2

In [7]:
# Place closed loop eigenvalues
K = ctrl.place(A, B, [-2+2j, -2-2j])
K

array([[0.8, 0.3]])

In [9]:
# Pole placement using Ackermann method
K = ctrl.acker(A, B, [-2+2j, -2-2j])
K

array([[0.8, 0.3]])

#### Ejemplo 2

Considere el problema de regular la población de un ecosistema mediante la modulación del suministro de alimentos. Para ello considere el modelo depredador-presa cuya dinámica está dada por las siguientes ecuaciones

\begin{equation}
 \label{eqn:predator_prey_sys}
 \begin{aligned}
  \dot{H} &= (r + u)H\left(1 - \frac{H}{k} \right) - \frac{aHL}{c+H}, \quad H\geq 0, \\
  \dot{L} &= b \frac{aHL}{c + H}  - dL, \quad L \geq 0.
 \end{aligned}
\end{equation}

En este sistema, $r$ denota la tasa de crecimiento de las liebres, $k$ la población máxima, $a$ el término que describe la disminución de las liebres en función de la población, $c$ representa la tasa de consumo de presas, $b$ el coeficiente de crecimiento de los linces y finalmente $d$ la tasa de mortalidad de los linces.

Analice el sistema en lazo abierto con $a=3.2$, $b=0.6$, $c=50$, $d=0.56$, $k=125$, $r = 1.6$.

#### Ejemplo 3

Considere un vehículo de dos ruedas como se muestra en la siguiente Figura

Un modelo que describe cómo la velocidad del vehículo depende del ángulo de dirección $\delta$. Además, $v$, representa la velocidad en el centro de la masa, $a$ la distancia de la rueda trasera, y $b$ la base de la rueda.

Sean $x$ e $y$ las coordenadas del centro de masa, $\theta$ en ángulo de rumbo y $\alpha$ el ángulo entre el vector de velocidad $v$ y la línea central del vehículo, entonces la relación entre $\alpha$ y el ángulo de dirección $\delta$ está dada como sigue

\begin{equation}
 \alpha(\delta) = \text{arctan}\left( \frac{a\tan(\delta)}{b} \right),
\end{equation}

donde $a := r_{a}\tan(\alpha)$, $b:= r_{a} \tan(\delta)$.

Asuma que las ruedas no patinan y que la velocidad de las ruedas traseras es $v_{0}$, entonces la velocidad del vehículo en su centro de masa es $v=v_{0}/\cos(\alpha)$. Por consiguiente, el movimiento de este punto está dado como sigue

\begin{equation}
 \label{eqn:vehiculo}
 \begin{aligned}
  \dot{x} &= v\cos(\alpha + \theta) = v_{0} \frac{\cos(\alpha + \theta)}{\cos(\alpha)}, \\
  \dot{y} &= v\sin(\alpha + \theta) = v_{0} \frac{\sin(\alpha + \theta)}{\cos(\alpha)}.
 \end{aligned}
\end{equation}

El ángulo $\theta$, afectado por el ángulo de dirección está dado por la siguiente relación

\begin{equation}
 \dot{\theta} = \frac{v_{0}}{r_{a}} = \frac{v_{0}}{b}\tan(\delta).
\end{equation}

Asuma que $\delta = 0$ y $\dot{\theta} = 0$ para encontrar el punto de equilibrio del sistema y proceda a linealizar \eqref{eqn:vehiculo}.


# Referencias
* Chen, C. T. (1995). *Analog and digital control system design: transfer-function, state-space, and algebraic methods*. Oxford University Press, Inc..
* Åström, K. J., & Murray, R. M. (2021). *Feedback systems: an introduction for scientists and engineers*. Princeton university press.